name: CI

on:
  push:
  pull_request: 

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:9.2
        env:
          # The MySQL docker container requires these environment variables to be set
          # so we can create and migrate the test database.
          # See: https://hub.docker.com/_/mysql
          MYSQL_DATABASE: adhesion_mc_backend_test
          MYSQL_ROOT_PASSWORD: adhesion_mc_backend
        ports:
          # Opens port 3306 on service container and host
          # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
          - 3306:3306
          # Before continuing, verify the mysql container is reachable from the ubuntu host
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - 
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2.12
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring
        env:
          update: true
      - uses: actions/checkout@v3
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Make test envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_APP_ENV: test
          envkey_DATABASE_URL:  mysql://root:adhesion_mc_backend@127.0.0.1:3306/adhesion_mc_backend?serverVersion=11.4&charset=utf8mb4
          file_name: .env.test.local
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      -
        name: Run migrations
        run: php bin/console -e test doctrine:migrations:migrate --no-interaction
      -
        name: Load fixtures
        run: php bin/console -e test doctrine:fixtures:load --no-interaction
      -
        name: Run PHPUnit
        run: php bin/phpunit
      -
        name: Doctrine Schema Validator
        run: php bin/console -e test doctrine:schema:validate