name: SSH Deploy to prod

on:
  push:
    branches:
      - main
      - feat/prepare-for-prod

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install PHP
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2.11
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring
        env:
          update: true
      - name: Check PHP Version
        run: php -v
      # Prepare .env file for production
      - name: Make production envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_APP_ENV: prod
          envkey_APP_DEBUG: false
          envkey_APP_SECRET: ${{ secrets.APP_SECRET }}
          envkey_DATABASE_URL:  ${{ secrets.DATABASE_URL }}
          envkey_CORS_ALLOW_ORIGIN: ${{ vars.CORS_ALLOW_ORIGIN }}
          envkey_JWT_PASSPHRASE: ${{ secrets.JWT_PASSPHRASE }}
          file_name: .env.local
      # Install backend dependencies (Composer)
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install Composer dependencies
        run: composer install --no-dev
      # Copying files and artifacts via SSH
      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ''
          rm: false
          source: "./"
          target: ${{ secrets.REMOTE_TARGET }}
